<?php
/**
 * Created by PhpStorm.
 * User: zhaoweijie
 * Date: 2019-01-03
 * Time: 21:50
 */

namespace Zwei\Kafka\Consumer\Forward;


use Zwei\Kafka\Consumer\Forward;

/**
 * 通用转发
 * Class CommonForward
 * @package Zwei\Kafka\Consumer\Forward
 */
class CommonForward extends Forward
{
    /**
     * 广播配置键: 广播到某个生产者
     */
    const CONFIG_KEY_PRODUCER = 'producer';

    /**
     * 广播配置键: 广播到某个主题名
     */
    const CONFIG_KEY_TOPIC = 'topic';

    /**
     * 广播到指定的生产者
     * @var string
     */
    protected $producerName = null;
    /**
     * 广播到指定的主题
     * @var string
     */
    protected $topicName = null;

    /**
     * @inheritdoc
     */
    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->producerName = $this->getConfig(self::CONFIG_KEY_PRODUCER);
        $this->topicName    = $this->getConfig(self::CONFIG_KEY_TOPIC);
    }
}