<?php
/**
 * Created by PhpStorm.
 * User: zhaoweijie
 * Date: 2019-01-02
 * Time: 19:15
 */

namespace Zwei\Kafka\Consumer\BroadCast;


use Zwei\Kafka\Event\EventHelper;
use Zwei\Kafka\Exceptions\Config\BroadCastConfigException;

/**
 * Class TargetBroadCast
 * @package Zwei\Kafka\Consumer\BroadCast
 */
class TargetBroadCast extends BroadCastAbstract
{
    /**
     * 广播配置键: 广播到某个生产者
     */
    const CONFIG_KEY_PRODUCER = 'producer';

    /**
     * 广播配置键: 广播到某个主题名
     */
    const CONFIG_KEY_TOPIC = 'topic';

    /**
     * 广播到指定的生产者
     * @var string
     */
    protected $producerName = null;
    /**
     * 广播到指定的主题
     * @var string
     */
    protected $topicName = null;

    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->producerName = $this->getConfig(self::CONFIG_KEY_PRODUCER);
        $this->topicName    = $this->getConfig(self::CONFIG_KEY_TOPIC);

    }

    /**
     * @inheritdoc
     */
    public function handle(array $event, $type)
    {
        return $this->broadCastEvent($event, $type, $this->producerName, $this->topicName);
    }
}